apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: am9vbWxhX3Bhc3M=
  MYSQL_USER: am9vbWxhX3VzZXI=
  MYSQL_DATABASE: am9vbWxhX2Ri
  MYSQL_DATABASE_HOST: ZGI=
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-backend-secrets
type: Opaque
data:
  # Valorile sunt codificate Base64, în producție utilizați kubectl create secret sau alt mecanism securizat
  AZURE_TEXT_ANALYTICS_API_KEY: MlBpN2JVQVlaWnBUREtwdllqV205ZUgyMmVoeFBLeDdZVW1tenJUMEp5TmxuSzhlRGg2akpRUUo5OUJEQUM1UnFMSlhKM3czQUFBYUFDT0dRYWdn
  AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWNhcmlieXRlc3RibG9iMTk7QWNjb3VudEtleT04c242YVo0ZzdjRURnOXFiSGdqVkhIbjlCK2xsVkJTakpmc2pRVndyTG1QcmJ1c0poMis1U0E4em9TWDluUUtocWthZnE0WnFKSDVXK0FTdHJtN2xHQT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  AZURE_SQL_PASSWORD: MTIzc2FiaW5zdGFuJA==
