FROM joomla:latest

# Copy existing Joomla data
COPY ./joomla_data/ /var/www/html/

# Correct permissions specifically for plugins
RUN chown -R www-data:www-data /var/www/html/

# Expose port 80
EXPOSE 80