apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-backend-deployment
  labels:
    app: azure-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-backend
  template:
    metadata:
      labels:
        app: azure-backend
    spec:
      containers:
        - name: azure-backend
          image: sabinghost19/azure-backend-service-node:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 3000
              name: node-api
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: azure-backend-config
            - secretRef:
                name: azure-backend-secrets
