apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: sabinghost19/custom-mysql:v2.0
          name: mysql
          ports:
            - containerPort: 3306
