apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
spec:
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
        - name: joomla
          image: tavigingu/joomla-cms:v1.0
          ports:
            - containerPort: 80
          env:
            - name: JOOMLA_DB_HOST
              value: "mysql-service"
            - name: JOOMLA_DB_USER
              value: "joomla_user"
            - name: JOOMLA_DB_PASSWORD
              value: "joomla_pass"
            - name: JOOMLA_DB_NAME
              value: "joomla_db"
