apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: tavigingu/mysql-db:v1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root_pass"
            - name: MYSQL_USER
              value: "joomla_user"
            - name: MYSQL_PASSWORD
              value: "joomla_pass"
            - name: MYSQL_DATABASE
              value: "joomla_db"
