version: "3.6"
services:
  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress_user # Schimbat de la root
      - WORDPRESS_DB_PASSWORD=password
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80

  db:
    build:
      context: ./mysql
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password # Setează parola pentru root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress_user # Creează un utilizator non-root
      - MYSQL_PASSWORD=password # Parola pentru utilizatorul non-root
    restart: always

volumes:
  db_data:
